apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  type: ExternalName
  externalName: vault.example.private
  ports:
  - name: http
    port: 80
    targetPort: 8200
    protocol: TCP
