# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 8200, host: 8200
  config.vm.network "forwarded_port", guest: 5432, host: 5432

  config.vm.network :private_network, ip: "192.168.82.82"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "4096"
  end

  config.vm.provision "shell" do |s|
    s.path = "https://raw.githubusercontent.com/rurumimic/no-check-certificate/main/ubuntu/focal64/update-certs.sh"
  end

  # config.vm.provision "docker"

  config.vm.provision :ansible do |ansible|
    ansible.playbook       = "ansible/playbook.yml"
    ansible.limit          = "all"
  end

end
