---
- hosts: all
  tasks:
    - name: Add the HashiCorp GPG key
      become: yes
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        validate_certs: no
    - name: Linux distribution
      shell: lsb_release -cs
      register: lsb_release
    - name: Add the official HashiCorp Linux repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main
    - name: Install Vault
      become: yes
      apt:
        name: vault
        state: present
        update_cache: yes
    - name: Configure Vault
      become: yes
      copy:
        src: vault/vault.hcl
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: 0640
    - name: Configure systemd
      become: yes
      copy:
        src: vault/vault.service
        dest: /etc/systemd/system/vault.service
        owner: root
        group: root
        mode: 0644
    - name: Start Vault
      become: yes
      systemd:
        name: vault
        state: started
        enabled: yes
