# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"

  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8200
  config.vm.network "forwarded_port", guest: 8200, host: 8200, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "4096"
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook       = "playbook.yml"
    ansible.limit          = "all"
    ansible.verbose        = true
  end
end

# cd /usr/local/share/ca-certificates
# sudo vi a.crt
# sudo update-ca-certificates
