---
- hosts: all
  tasks:
    - name: Add the HashiCorp GPG key
      become: yes
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        validate_certs: no
    - name: Linux distribution
      shell: lsb_release -cs
      register: lsb_release
    - name: Add the official HashiCorp Linux repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main
    - name: Install Vault
      become: yes
      apt:
        name: vault
        state: present
        update_cache: yes
    - name: Create a plugin directory
      become: yes
      file:
        path: /opt/vault/plugins
        state: directory
        recurse: yes
        owner: vault
        group: vault
    - name: Configure systemd
      become: yes
      copy:
        src: vault.service
        dest: /etc/systemd/system/vault.service
        owner: root
        group: root
        mode: 0644
